# Generated by Django 5.2.7 on 2025-10-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Equipamento')),
                ('ca', models.CharField(max_length=50, verbose_name='C.A. (Certificado de Aprovação)')),
                ('quantidade_total', models.PositiveIntegerField(default=0, verbose_name='Quantidade Total')),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0, verbose_name='Quantidade Disponível')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
