# Generated by Django 5.2.7 on 2025-10-31 22:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_equipamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Empréstimo')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='gestao.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='gestao.equipamento')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
