[pytest]
DJANGO_SETTINGS_MODULE = projeto_epi.settings
<<<<<<< HEAD
python_files = tests.py test_*.py


=======
python_files = tests.py test_*.py *_tests.py
>>>>>>> 76ed915e5c61176c68d04b29881b42a925173068
